--- a/.github/workflows/prettier.yml
+++ b/.github/workflows/prettier.yml
@@ -1,8 +1,8 @@
 name: Run Prettier Lints
 
 on:
-  - push
-  - pull_request
+  push:
+  pull_request:
 
 jobs:
   prettier:
@@ -17,4 +17,4 @@
     - name: Prettier
       uses: Borales/actions-yarn@master
       with:
-        args: run prettier-check
+        args: run prettier-check